### ISSUE TITLE
How is this approach related to Fourier Domain Convnets?

### ISSUE THREAD

**Issue by CeaVi** [adobe/antialiased-cnns#6]
Hi,

interesting approach! How is this related to networks doing pooling in Fourier Domain, as discussed in http://ecmlpkdd2017.ijs.si/papers/paperID11.pdf (and the references therein)?

**Comment by richzhang** [comment]
We show compatible usage of antialiasing with existing downsampling layers. Whether one wants to do the antialiasing in Fourier domain (rather than simple 3x3, 5x5 kernels in spatial domain that we use) is an orthogonal choice.

The referenced paper left the following as "future work":

> For future work the authors intend to investigate how the Fourier layers can be optimised and implemented with respect to other network architectures that have achieved state-of-the-art accuracies [ResNet, Inception].

In our paper, we show improvement in Imagenet performance on popular architectures such as ResNet.
